version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    image: don361/pygoat
    # command: gunicorn --bind 0.0.0.0:8000 --workers 6 pygoat.wsgi
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - migration
      - db
  migration:
    image: don361/pygoat
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - db